server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: jobsearch

  datasource:
    url: jdbc:h2:./db/jobsearch;AUTO_SERVER=TRUE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

logging:
  file:
    path: logs
  level:
    root: info
    kg.attractor.jobsearch: debug
    com.zaxxer.hikari: error
    org.apache.tomcat: error
    liquibase: error
    org.springframework.security: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"